name: EX Emulators

on: [push, pull_request]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["PCE.emu"]
    container: cirrusci/android-sdk:30-ndk
 
    steps:
    - name: Checkout emu-ex-plus-alpha repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Decode debug keystore
      env:
        DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
      run: |
        if [ -z "$DEBUG_KEYSTORE" ]
        then
           echo "No debug keystore value"
        else
           echo $DEBUG_KEYSTORE > debug.keystore.base64
           base64 --decode debug.keystore.base64 > debug.keystore
           sudo cp -f debug.keystore /root/.android/.
        fi
        
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends autoconf automake autopoint bash binutils-arm-linux-gnueabi clang cmake file gawk gettext git libtool libtool-bin llvm make nasm openjdk-8-jdk pkg-config unzip
        sudo apt-get upgrade -y
        echo y | sdkmanager "cmake;3.18.1"
        
    - name: Download and unzip NDK
      working-directory: /opt/android-sdk-linux/ndk
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -qq ./android-ndk-r25b-linux.zip
        
    - name: Set up environment
      run: |
        mkdir imagine-sdk
        mkdir EX-Emulators
        echo "ANDROID_NDK_PATH=/opt/android-sdk-linux/ndk/android-ndk-r25b" >> $GITHUB_ENV
        echo "EMUFRAMEWORK_PATH=${{ github.workspace }}/EmuFramework" >> $GITHUB_ENV
        echo "IMAGINE_PATH=${{ github.workspace }}/imagine" >> $GITHUB_ENV
        echo "IMAGINE_SDK_PATH=${{ github.workspace }}/imagine-sdk" >> $GITHUB_ENV

    - name: Run script
      run: |
        cd imagine/bundle/all
        chmod +x ./makeAll-android.sh
        ./makeAll-android.sh install
      shell: bash
          
    - name: Build environment
      run: |
        make -f $IMAGINE_PATH/android-release.mk install V=1 -j2
        make -f $EMUFRAMEWORK_PATH/android-release.mk config -j2
        make -f $EMUFRAMEWORK_PATH/android-release.mk install V=1 -j2

    - name: Build PCE.emu
      if: ${{ matrix.image == 'PCE.emu' }}
      run: |        
        cd PCE.emu
        make -f android-release.mk android-apk V=1 -j2

    - name: Copy PCE.emu artifact
      if: ${{ matrix.image == 'PCE.emu' }}
      run: |
        cp PCE.emu/target/android-release/build/outputs/apk/release/PceEmu-release.apk EX-Emulators/PceEmu-release.apk
     
    - name: Upload PCE.emu artifact
      uses: actions/upload-artifact@v2
      if: ${{ matrix.image == 'PCE.emu' }}
      with: 
        name: PCEemu
        path: ${{ github.workspace }}/PCE.emu/target/android-release/build/outputs/apk/release/PceEmu-release.apk

    - name: Upload EX-Emulators artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: EX-Emulators
        path: EX-Emulators/
